### ISSUE TITLE
MODULE_VERSION not updated to 1.10

### ISSUE THREAD

**Issue by totaam** [jd-boyd/python-lzo#13]
$ wget https://pypi.python.org/packages/source/p/python-lzo/python-lzo-1.10.tar.gz
$ tar -zxf python-lzo-1.10.tar.gz 
$ grep "define MODULE_VERSION" ./python-lzo-1.10/lzomodule.c 
#define MODULE_VERSION  "1.09"

And after installing it you find:
$ python -c "import lzo;print(lzo.__version__)"
1.09

**Comment by jd-boyd** [comment]
Well that is just embarrassing.  I will release a fix soon, but I want to figure out a way to prevent that over sight again before doing so.

**Comment by jd-boyd** [comment]
OK, 1.11 has been released with this fixed.

I've added a test to check for the mismatch, and I started a more automated deploy to pypi that will only work if the tests pass.
