### ISSUE TITLE
Support lzo1y_decompress_safe

### ISSUE THREAD

**Issue by grucin** [jd-boyd/python-lzo#24]
Is there any plan to support _lzo1y_decompress_safe_ in decompress method?

**Comment by jd-boyd** [comment]
Thank you for your question.

There was no plan to do so prior to your inquiry.  I would not be opposed to that if someone wanted to make a pull request for it though.  Also, with more detail, I'd be willing to consider doing it myself when I have time.

I'm sad to confess that I'm not really sure what the difference between `lzo1y_decompress_safe` and `lzo1x_decompress_safe` is.  Reviewing what is currently implemented, I see so far this python module uses only lzo1x functions.

Would it suffice to just add an optional argument to the decompress method to specify whether 
LZO1, LZO1A, LZO1B, LZO1C, LZO1F, LZO1X, LZO1Y, LZO1Z is to be used?

**Comment by grucin** [comment]
Hi Joshua,

I would be glad if you add that optional argument to the decompress method.

**Comment by sektoid0** [comment]
Hi,

Wonder if you are still planning to implement this feature? I would need `lzo1z_decompress_safe` so what you have proposed would work for me too.

Thanks!

**Comment by jd-boyd** [comment]
@sektoid0 I'd be happy to review and accept a pull request for it if you wanted to make one.  Also, I am available for paid work if people need it.  Otherwise, I don't have a lot of time to dedicate to new features here for a library I don't use much anymore.
