### ISSUE TITLE
macOS Mojave install error

### ISSUE THREAD

**Issue by suliveevil** [jd-boyd/python-lzo#38]
suliveevil@:~% pip3 install python-lzo
Collecting python-lzo
  Downloading https://files.pythonhosted.org/packages/af/60/41f17f56c920a956f1d4b9f04f9755c045b2b06b9dd933b33cdd37ab9fd7/python-lzo-1.12.tar.gz
Installing collected packages: python-lzo
  Running setup.py install for python-lzo ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j5/dbjgjmz56z37dybvp7z3s3rw0000gn/T/pip-install-v4cawhuk/python-lzo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/j5/dbjgjmz56z37dybvp7z3s3rw0000gn/T/pip-record-guf446qf/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'lzo' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.7
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/include/lzo -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c lzomodule.c -o build/temp.macosx-10.9-x86_64-3.7/lzomodule.o
    lzomodule.c:35:10: fatal error: 'lzo/lzo1x.h' file not found
    #include <lzo/lzo1x.h>
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

`Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j5/dbjgjmz56z37dybvp7z3s3rw0000gn/T/pip-install-v4cawhuk/python-lzo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/j5/dbjgjmz56z37dybvp7z3s3rw0000gn/T/pip-record-guf446qf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/j5/dbjgjmz56z37dybvp7z3s3rw0000gn/T/pip-install-v4cawhuk/python-lzo/`

**Comment by jd-boyd** [comment]
This looks to be the same as #23.
