### ISSUE TITLE
lzo.lib file needed

### ISSUE THREAD

**Issue by sophieroos** [jd-boyd/python-lzo#39]
In the process of working on [this package](https://github.com/pazaan/decoding-contour-next-link), I need to install `pip install python-lzo`. But the problem is that it expects a `lzi.lib` file which I can nowhere find on the internet.

I hope you can help me.

**Comment by jd-boyd** [comment]
What platform are you installing on?

**Comment by sophieroos** [comment]
I tried it on Windows using pip and the download link http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz

**Comment by BiatuAutMiahn** [comment]
What version of MSVC? 2019 fails

**Comment by jd-boyd** [comment]
@BiatuAutMiahn could you open a new issue about the MSVC 2019 failures?

**Comment by jd-boyd** [comment]
@sophieroos I apologize for not getting back to you in a timely manner.  I'm not sure why you get the error you report.  It would have helped if the actual error message and lines proceeding it were pasted in as well. Also, as I understand it, the file you are missing should be built as part of the install process, so it seems like there should be some other sort of build error from earlier in the process. 

There isn't really enough to go on here for your specific problem, so if you can't post more (and I certainly understand you might not want to after this time), I'm going to have to close it.

**Comment by Tuo-ZHANG** [comment]
> @sophieroos I apologize for not getting back to you in a timely manner. I'm not sure why you get the error you report. It would have helped if the actual error message and lines proceeding it were pasted in as well. Also, as I understand it, the file you are missing should be built as part of the install process, so it seems like there should be some other sort of build error from earlier in the process.
> 
> There isn't really enough to go on here for your specific problem, so if you can't post more (and I certainly understand you might not want to after this time), I'm going to have to close it.

I have encounted the same problem.
