### ISSUE TITLE
File not found error when pip installing python-lzo on Kali 2020.1

### ISSUE THREAD

**Issue by Pep00000001** [jd-boyd/python-lzo#47]
running install threw the error :

**> No such file or directory
>      35 | #include <lzo/lzo1x.h
>         |          ^~~~~~~~~~~~~**

After installing liblzo2-dev this issue was fixed:
apt install liblzo2-dev

**Comment by jd-boyd** [comment]
On review, this isn't really a bug in the package. There is no standard way to make pip installing a package install apt dependencies, and the install directions in the README for ubuntu did specify running that apt command.  I'm closing this. If someone can point me to documentation for a better way to do it, feel free to open a new issues.

**Comment by hzcheney** [comment]
> On review, this isn't really a bug in the package. There is no standard way to make pip installing a package install apt dependencies, and the install directions in the README for ubuntu did specify running that apt command. I'm closing this. If someone can point me to documentation for a better way to do it, feel free to open a new issues.

Thanks a lot! That really helps me! I have a macOS 12.5 with MBP 2017.
