### ISSUE TITLE
Make a new release with Python 3.10 support

### ISSUE THREAD

**Issue by sbraz** [jd-boyd/python-lzo#52]
Hello,
It looks like it took a few commits to make the project work with Python 3.10, would it please be possible to create a new release with all these so that we don't have to backport them downstream in the Gentoo package?

**Comment by jd-boyd** [comment]
Seems like a good reason to get it done. I will try to get it done soon.

**Comment by jd-boyd** [comment]
A new release has been made. I don't currently have python 3.10 setup to test against, so please let me know if the new release works with it. I believe I heard that the unit tests don't currently work due to nose not support 3.10.

**Comment by sbraz** [comment]
Tests work with v1.14 and Python 3.10, thanks.
