### ISSUE TITLE
decompress Warn: LZO Error: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by danyhm** [jd-boyd/python-lzo#54]
hello,

i get this error with python 3.10 on windows, version1.12
decompress Warn: LZO Error: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

it's included in this repo
https://github.com/jrspruitt/ubi_reader

didn't have this problem before

**Comment by nsoranzo** [comment]
I think this was fixed in https://github.com/jd-boyd/python-lzo/pull/46 , but it hasn't been released in a new PyPI package, see https://github.com/jd-boyd/python-lzo/issues/52

**Comment by eacmen** [comment]
+1 for a new release needed. Happy to help push a release over the finish line.

**Comment by jd-boyd** [comment]
A new release was made, so I'm closing this.
