### ISSUE TITLE
 Installation failure

### ISSUE THREAD

**Issue by majunze2001** [jd-boyd/python-lzo#59]
I am using macOS Monterey 12.2.1 on M1 chip and the installation failed.

Building wheels for collected packages: python-lzo
  Building wheel for python-lzo (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'lzo' extension
      creating build
      creating build/temp.macosx-10.14-arm64-3.8
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c lzomodule.c -o build/temp.macosx-10.14-arm64-3.8/lzomodule.o
      lzomodule.c:37:10: fatal error: 'lzo/lzo1x.h' file not found
      #include <lzo/lzo1x.h>
               ^~~~~~~~~~~~~
      1 error generated.
      error: command 'clang' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-lzo
  Running setup.py clean for python-lzo
Failed to build python-lzo
Installing collected packages: python-lzo
  Running setup.py install for python-lzo ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for python-lzo did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running install
      running build
      running build_ext
      building 'lzo' extension
      creating build
      creating build/temp.macosx-10.14-arm64-3.8
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c lzomodule.c -o build/temp.macosx-10.14-arm64-3.8/lzomodule.o
      lzomodule.c:37:10: fatal error: 'lzo/lzo1x.h' file not found
      #include <lzo/lzo1x.h>
               ^~~~~~~~~~~~~
      1 error generated.
      error: command 'clang' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-lzo

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by damian-adelaide** [comment]
Same issue on osx 12.3.1/M1

**Comment by 1over137** [comment]
same issue here, on AppVeyor Mac image.

**Comment by link-ding** [comment]
same issue

**Comment by link-ding** [comment]
> 

I already install lzo in my computer by using `brew install lzo`.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/49264539/167137155-94576100-9773-4ebc-aaa2-6980eab076aa.png">

**Comment by Lindanvdw** [comment]
same

**Comment by OlivierLaflamme** [comment]
same issue here

**Comment by blluv** [comment]
CFLAGS=-I$(brew --prefix)/include LDFLAGS=-L$(brew --prefix)/lib pip3 install python-lzo

**Comment by damian-adelaide** [comment]
Now getting import error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/lzo.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '___lzo_init_v2'
```

**Comment by ruanimal** [comment]
So, why not upload wheel pkg to pypi ?
