### ISSUE TITLE
New release for Python 3.11 and v1.15/v1.16 ?

### ISSUE THREAD

**Issue by AkechiShiro** [jd-boyd/python-lzo#68]
Hi, is it possible that a new release be made, the latest tag, is on v1.14 but NEWS.md contains v1.15 and I've created a package for Arch Linux using PKGBUILD and installing it, inspecting the path looks like that v1.16 is currently being developed ?

Could a release tag be created for v1.15 or maybe if v1.16 is ready a release tag be made for it ?

**Comment by jd-boyd** [comment]
While I noted 1.16, it looks like I never tagged or uploaded releases for 1.15, so I'm going to try to get that finished up. I also have requests for Windows wheels being published (as noted in a comment on #65).

**Comment by jd-boyd** [comment]
OK, I believe that 1.15 is completed, including 3.11 support and Windows wheels.

**Comment by AkechiShiro** [comment]
Thanks !
