### ISSUE TITLE
Anything blocking a new release?

### ISSUE THREAD

**Issue by abadger** [jd-boyd/python-lzo#9]
I was taking a look for whether an lzo module existed for python3 and found that support had been merged here and you were the pypi owner as well.  Any plans for a release so that distros can start consuming the improvements and porting effort?

**Comment by jd-boyd** [comment]
It looks like the python 3 stuff merged is incomplete.  That is the hold up of releasing 1.09 to Pypi.

**Comment by jd-boyd** [comment]
OK, 1.09 with python 3 support is released. https://pypi.python.org/pypi/python-lzo/

**Comment by abadger** [comment]
Thanks!
